sports_card_analytics:
  target: {{ env_var('DBT_TARGET', 'dev') }}
  outputs:
    dev:
      type: snowflake
      account: {{ env_var('SNOWFLAKE_ACCOUNT') }}
      user: {{ env_var('SNOWFLAKE_USER') }}
      password: {{ env_var('SNOWFLAKE_PASSWORD') }}
      role: {{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}
      warehouse: {{ env_var('SNOWFLAKE_WAREHOUSE', 'ANALYTICS_WH') }}
      database: {{ env_var('SNOWFLAKE_DATABASE', 'SPORTS_CARD_ANALYTICS') }}
      schema: {{ env_var('SNOWFLAKE_SILVER_SCHEMA', 'SILVER') }}
      threads: 4
      client_session_keep_alive: false
