AWSTemplateFormatVersion: "2010-09-09"
Description: CloudWatch alarms and SNS notifications for AmazonMQ ingestion Lambda.

Parameters:
  LambdaFunctionName:
    Type: String
    Default: amazonmq-ingestion-lambda
  AlarmEmail:
    Type: String
    Default: example@example.com
    Description: Email to subscribe to alarm notifications (replace with real address)
  ErrorThreshold:
    Type: Number
    Default: 0
  ThrottleThreshold:
    Type: Number
    Default: 0
  DurationP95ThresholdMs:
    Type: Number
    Default: 25000

Resources:
  IngestionAlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: amazonmq-ingestion-alarms

  IngestionAlarmSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref IngestionAlarmTopic
      Endpoint: !Ref AlarmEmail

  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${LambdaFunctionName}-errors"
      AlarmDescription: Lambda Errors > 0 for 5 minutes
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref ErrorThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref IngestionAlarmTopic

  LambdaThrottlesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${LambdaFunctionName}-throttles"
      AlarmDescription: Lambda Throttles > 0 for 5 minutes
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref ThrottleThreshold
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref IngestionAlarmTopic

  LambdaDurationP95Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${LambdaFunctionName}-duration-p95"
      AlarmDescription: Lambda p95 duration exceeds threshold
      Namespace: AWS/Lambda
      MetricName: Duration
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      ExtendedStatistic: p95
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Ref DurationP95ThresholdMs
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref IngestionAlarmTopic

Outputs:
  AlarmTopicArn:
    Value: !Ref IngestionAlarmTopic
