-- Snowflake DDL for Sports Card Analytics Platform

-- Warehouses
CREATE OR REPLACE WAREHOUSE ANALYTICS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database and schemas
CREATE OR REPLACE DATABASE SPORTS_CARD_ANALYTICS;
CREATE OR REPLACE SCHEMA SPORTS_CARD_ANALYTICS.RAW;
CREATE OR REPLACE SCHEMA SPORTS_CARD_ANALYTICS.SILVER;
CREATE OR REPLACE SCHEMA SPORTS_CARD_ANALYTICS.GOLD;

-- File formats and stages (assumes JSON events landed in S3)
CREATE OR REPLACE FILE FORMAT SPORTS_CARD_ANALYTICS.RAW.JSON_EVENTS
  TYPE = 'JSON'
  STRIP_OUTER_ARRAY = TRUE;

CREATE OR REPLACE STAGE SPORTS_CARD_ANALYTICS.RAW.S3_EVENTS_STAGE
  URL = 's3://sports-card-events/raw/events/'
  FILE_FORMAT = SPORTS_CARD_ANALYTICS.RAW.JSON_EVENTS;

-- RAW events table (payload stored as VARIANT)
CREATE OR REPLACE TABLE SPORTS_CARD_ANALYTICS.RAW.EVENTS (
  EVENT_ID STRING,
  SOURCE STRING,
  EVENT_TYPE STRING,
  PAYLOAD VARIANT,
  INSERTED_AT TIMESTAMP_TZ
);

-- Optional: cluster for pruning and dedupe patterns
ALTER TABLE SPORTS_CARD_ANALYTICS.RAW.EVENTS
  CLUSTER BY (EVENT_TYPE, INSERTED_AT);

-- Example COPY INTO (can be run by Airflow or Snowpipe)
-- COPY INTO SPORTS_CARD_ANALYTICS.RAW.EVENTS
--   FROM @SPORTS_CARD_ANALYTICS.RAW.S3_EVENTS_STAGE
--   FILE_FORMAT = (FORMAT_NAME = SPORTS_CARD_ANALYTICS.RAW.JSON_EVENTS)
--   MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
